[package]
name = "vcpu"
version = "0.1.0"
authors = ["Dennis Heinze <dennisjp.heinze@gmail.com>"]

[dependencies]
num = "0.1"
num-integer = "0.1"
num-traits = "0.2"
num-derive = "0.2"

byteorder = "1"