language = "C"
include_guard = "VCPU_H"
cpp_compat = true

[export]
prefix = "Vcpu"
renaming_overrides_prefixing = true

[export.rename]
"VcpuResult" = "VcpuResult"

[parse]
parse_deps = true
include = ["vcpu-interop", "vcpu", "vex"]
