[package]
name = "vex"
version = "0.1.0"
authors = ["Dennis Heinze <dennisjp.heinze@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.32.0"
vcpu = { path = ".." }
vasm = { path = "../vasm" }
vexfile = { path = "../vexfile" }